<table class="types_tables">
    <tr>
        <td><div class="types type_3"></div></td>
        <td> - tavakaup</td>
        <td class="space">&nbsp;</td>
        <td><div class="types type_4"></div></td>
        <td> - jahutuskaup (+2 - +6)</td>
        <td class="space">&nbsp;</td>
        <td><div class="types type_5"></div></td>
        <td> - sügavkülma tooted</td>
                            
    </tr>
</table>
<p>Kõik hinnad tellimiskeskuses on käibemaksuta tükihinnad Eurodes (Jungenti hulgihinnakirjahind) välja arvatud kaalukaup! E-tellimusest arve koostamisel rakenduvad lepingulised allahindlused ja eripakkumishinnad. Tellimuste miinimumkoguseks toote kohta on
hulgipakend.</p>
<br />