
<?php
$storeId = Mage::app()->getStore()->getId();

/*
  $product    = Mage::getModel('catalog/product');
  $todayDate  = $product->getResource()->formatDate(time());
  $products   = $product->setStoreId($storeId)->getCollection()
  ->addAttributeToSelect(array('name', 'price', 'small_image','manufacturer'), 'left')
  ->addAttributeToSelect(array('special_price', 'special_from_date', 'special_to_date'), 'left')
  ->addAttributeToSelect('status')
  ->addAttributeToSort('special_to_date','desc')

  ;
 */


$todayDate = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
$products = Mage::getResourceModel('catalogsearch/advanced_collection')
                ->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes());
$products->addAttributeToFilter('special_from_date', array('date' => true, 'to' => $todayDate))
        ->addAttributeToFilter('special_to_date',
                array('or' => array(
                        0 => array('date' => true, 'from' => $todayDate),
                        1 => array('is' => new Zend_Db_Expr('null')))
                ), 'left');
$productCategories = array();
foreach ($products as $product) {
    $categoryId = $product->getCategoryIds();
//    $productCategories[] = $categoryId;
    $productCategories[$categoryId[0]]['products'][] = $product;
    $_category = Mage::getModel('catalog/category')->load($categoryId[0]);
    if ($_category->getName()) {
        $productCategories[$categoryId[0]]['name'] = $_category->getName();
    } else {
        $productCategories[$categoryId[0]]['name'] = 'no category';
    }
}
?>
<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <div id='cart_current'>
    <?= $this->getChildHtml('cart_current') ?>
</div>
<?php else: ?>
<?= $this->getChildHtml('customer_form_login') ?>
<?php endif; ?>

        <div class="hr"></div>
        <h2>Eripakkumised:</h2>

        <div class="colored table items">
            <table>
                <thead>
                <th class="first">Toote nr.</th>
                <th>Toote nimetus</th>
                <th>Ühiku kogus</th>
                <th>Hulgi-hind</th>
                <th>Soodustus</th>
                <th>Soodus-hind</th>
                <th>Brand</th>
                <th>Kogus</th>
                <th class="last">Tüüp</th>
                </thead>
                <tbody>
            <?php
            $totalcount = count($products);
            if ($products) {
                $i = 0;
                foreach ($productCategories as $productsInArr) {
 ?>

                    <tr class="subcat ">
                        <td class="first last left nohover" colspan="7"><?php echo $productsInArr['name'];?></td>
                    </tr>        
            <?php
                    foreach ($productsInArr['products'] as $product) {
                        $i++;
                        $_product = Mage::getModel('catalog/product')->load($product->getData('entity_id'));
            ?>
                        <tr <?php
                        if ($i == 1) {
                            echo ' class="" ';
                        } elseif ($i == $totalcount)
                            echo ' class="last" '
            ?>>
                            <td class="first"><?= $_product->getSku() ?></td>
                            <td class="left" width="40%"><?php echo $_product->getName(); if($_product->getSoodustus()){ echo ' <span style="color:red;">' . $_product->getSoodustus() . '</span>';}?>
                                <div class="himage"><img src='<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(265); ?>' /></div>
                            </td>
                            <td><?= $_product->getData('unit_quantity') ?></td>
                       	<td><?= number_format($_product->getPrice(), 2) ?></td>
                        <td><?php
                            echo number_format(100 - (($_product->getSpecialPrice() / $_product->getPrice()) * 100), 2);
            ?>%</td>
                         <td><?= number_format($_product->getSpecialPrice(), 2) ?></td>
                        <td><?= $product->getAttribute('manufacturer') ?></td>
                        <td width="11%"><input  type="text" name='qty'/>
                            <input type="hidden" name='product_id' value='<?= $_product->getId() ?>'/>
                            <div class="add"></div></td>
                        <td class="last">
                            <div class="types type_<?= $_product->getTuup() ?>"></div>
                                </td>
                            </tr>
<?php
                        }
                    }
?>
                    <tr>
                        <td colspan="9"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>print">Prindi eripakkumised</a></td>
                    </tr>
<?php } ?>
        </tbody>
    </table>
</div>