<?php
$storeId = Mage::app()->getStore()->getId();


$todayDate = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
$products = Mage::getResourceModel('catalogsearch/advanced_collection')
                ->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes());
$products->addAttributeToFilter('special_from_date', array('date' => true, 'to' => $todayDate))
        ->addAttributeToFilter('special_to_date',
                array('or' => array(
                        0 => array('date' => true, 'from' => $todayDate),
                        1 => array('is' => new Zend_Db_Expr('null')))
                ), 'left');
?>
<div class="hr">
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>/skin/frontend/default/jungent/images/header.png"/></div>
<p>Special offers on <?php echo date("d/M/Y");?></p>
<div class="colored table items">
            <table>
                <thead>
                <th class="first">Toote nr.</th>
                <th>Toote nimetus</th>
                <th>Ühiku kogus</th>
                <th>Ühiku hind</th>
                <th>Soodustus</th>
                <th>KM-ta</th>
                <th>Brand</th>
                </thead>
                <tbody>
<?php
        $totalcount = count($products);
        if ($products){
            $i = 0;
            foreach ($products as $product){ $i++;
                $_product = Mage::getModel('catalog/product')->load($product->getData('entity_id'));
            ?>
                <tr <?php
                if ($i == 1) {
                    echo ' class="" ';
                } elseif ($i == $totalcount)
                    echo ' class="last" '
            ?>>
                    <td class="first"><?= $_product->getSku() ?></td>
                    <td class="left" width="40%"><?= $_product->getName() ?>
                    </td>
                    <td><?= $_product->getData('unit_quantity') ?></td>
                    <td><?= number_format($_product->getSpecialPrice(), 2) ?></td>
                    <td><?php
                    echo number_format(100 - (($_product->getSpecialPrice() / $_product->getPrice()) * 100), 2);
            ?>%</td>
                <td><?= number_format($_product->getPrice(), 2) ?></td>
                <td><?= $product->getAttribute('manufacturer') ?></td>
            </tr>
            <?php } ?>
                <?php } ?>
        </tbody>
    </table>
</div>
<script>
window.print();
window.location.href = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>';
</script>
<style>
    table tr td,th{
        text-align: center;
        padding-right: 35px;
}
</style>