<div class="block block-facebook">
                             <div class="block-header"></div>
                             <div class="block-content">
                                    <iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2FJungent.Foodservice&amp;width=200&amp;colorscheme=light&amp;show_faces=true&amp;stream=true&amp;header=false&amp;height=397" scrolling="no" frameborder="0" 
                                     style="border:none;
                                    background-color: white;
                                     overflow:hidden; width:200px; height:395px;" allowTransparency="true"></iframe>
                            </div>
                             </div>